### ISSUE TITLE
Failures: 271

### ISSUE THREAD

**Issue by Ezharjan** [babelcloud/LLM-RGB#21]
After running `npm run start`, it outputs error as follows:
```
Run promptfoo view to use the local web viewer
Run promptfoo share to create a shareable URL
Run promptfoo feedback to share feedback with the developers of this tool
=========================================================================================================================================================================================================
Successes: 14
Failures: 271
Token usage: Total 0, Prompt 0, Completion 0, Cached 0
Done.

> llm-rgb@1.0.0 render
> ts-node generateEvalScore.ts && ts-node render.ts

Data loaded from JSON file: /home/alex/.promptfoo/output/latest.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-score.json
Successfully wrote testStats to /home/alex/.promptfoo/output/latest-stats.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-raw.json
/home/alex/Documents/EvaluateLLM/render.ts:43
scoreData.forEach((item: any) => {
          ^
TypeError: Cannot read properties of undefined (reading 'push')
    at /home/alex/Documents/EvaluateLLM/render.ts:63:33
    at Array.forEach (<anonymous>)
    at /home/alex/Documents/EvaluateLLM/render.ts:62:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/alex/Documents/EvaluateLLM/render.ts:43:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/home/alex/Documents/EvaluateLLM/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/home/alex/Documents/EvaluateLLM/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
(base) alex@fst-computer:~/Documents/EvaluateLLM$ npm run start

> llm-rgb@1.0.0 start
> npm run eval;npm run render && npm run share


> llm-rgb@1.0.0 eval
> promptfoo eval --no-cache

```

**Comment by Ezharjan** [comment]
The failure ID changes on each run.
When I run it again it shows the following errors:
```
Successes: 10
Failures: 275
Token usage: Total 0, Prompt 0, Completion 0, Cached 0
Done.

> llm-rgb@1.0.0 render
> ts-node generateEvalScore.ts && ts-node render.ts

Data loaded from JSON file: /home/alex/.promptfoo/output/latest.json
Successfully wrote testStats to /home/alex/.promptfoo/output/latest-stats.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-score.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-raw.json
/home/alex/Documents/EvaluateLLM/render.ts:43
scoreData.forEach((item: any) => {
          ^
TypeError: Cannot read properties of undefined (reading 'push')
    at /home/alex/Documents/EvaluateLLM/render.ts:63:33
    at Array.forEach (<anonymous>)
    at /home/alex/Documents/EvaluateLLM/render.ts:62:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/alex/Documents/EvaluateLLM/render.ts:43:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/home/alex/Documents/EvaluateLLM/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/home/alex/Documents/EvaluateLLM/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
```

With a different failure ID of 275.

**Comment by zhlmmc** [comment]
yes, this issue will be fixed soon

**Comment by zhlmmc** [comment]
Please double check if your main branch is updated and make sure you run npm install first. If the problem persists try command:  npx promptfoo@latest eval 
and then run npm run start

**Comment by Ezharjan** [comment]
> Please double check if your main branch is updated and make sure you run npm install first. If the problem persists try command: npx promptfoo@latest eval and then run npm run start

Thanks! I'll try it immediately.

**Comment by Ezharjan** [comment]
The problem still exists.
## Reproduce
1. Clone this repository.
2. Run `sudo npm i`.
3. Run `npm run start`
4. Outputs the following error as mentioned above:
```
=========================================================================================================================================================================================================
✔ Evaluation complete.

Run promptfoo view to use the local web viewer
Run promptfoo share to create a shareable URL
Run promptfoo feedback to share feedback with the developers of this tool
=========================================================================================================================================================================================================
Successes: 16
Failures: 269
Token usage: Total 0, Prompt 0, Completion 0, Cached 0
Done.

> llm-rgb@1.0.0 render
> ts-node generateEvalScore.ts && ts-node render.ts

Data loaded from JSON file: /home/alex/.promptfoo/output/latest.json
Successfully wrote testStats to /home/alex/.promptfoo/output/latest-stats.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-score.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-raw.json
/home/alex/Documents/LLM-RGB/render.ts:43
scoreData.forEach((item: any) => {
          ^
TypeError: Cannot read properties of undefined (reading 'push')
    at /home/alex/Documents/LLM-RGB/render.ts:63:33
    at Array.forEach (<anonymous>)
    at /home/alex/Documents/LLM-RGB/render.ts:62:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/alex/Documents/LLM-RGB/render.ts:43:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/home/alex/Documents/LLM-RGB/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/home/alex/Documents/LLM-RGB/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
```
6. Run `sudo npx promptfoo@latest eval` and then run `npm run start` again.
7. Outputs the same error with different failure ID again.
9. Remove the [this line](https://github.com/babelcloud/LLM-RGB/blob/a9fd50237ed911429c97d231b9227144a6c413ed/package.json#L28) in `package.json`. 
10. Remove `node_modules` in this directory via `sudo rm -rf ./node_modules` and try reinstall them again via `sudo npx promptfoo@latest eval` first and then run `sudo npm i` to install the latest version of `promptfoo` manually and install the other dependancies through `package.json`. (I even tried `npm install -g promptfoo@latest` for installing the latest version of `promotfoo`).
11. Run `npm run start` again, outputs the other errors as follows:
```
(base) alex@fst-computer:~/Documents/LLM-RGB$ npm run start

> llm-rgb@1.0.0 start
> npm run eval;npm run render && npm run share


> llm-rgb@1.0.0 eval
> promptfoo eval --no-cache

Cache is disabled.
node:fs:600
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/alex/Documents/LLM-RGB/testcases/testcases/001_requirement_check_prompt.txt'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at loadTestWithVars (/home/alex/Documents/LLM-RGB/node_modules/promptfoo/dist/src/testCases.js:99:40)
    at readTest (/home/alex/Documents/LLM-RGB/node_modules/promptfoo/dist/src/testCases.js:119:26)
    at loadTestsFromGlob (/home/alex/Documents/LLM-RGB/node_modules/promptfoo/dist/src/testCases.js:137:32)
    at readTests (/home/alex/Documents/LLM-RGB/node_modules/promptfoo/dist/src/testCases.js:161:36)
    at Command.<anonymous> (/home/alex/Documents/LLM-RGB/node_modules/promptfoo/dist/src/main.js:291:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/alex/Documents/LLM-RGB/testcases/testcases/001_requirement_check_prompt.txt'
}

Node.js v18.14.2

> llm-rgb@1.0.0 render
> ts-node generateEvalScore.ts && ts-node render.ts

Data loaded from JSON file: /home/alex/.promptfoo/output/latest.json
Successfully wrote testStats to /home/alex/.promptfoo/output/latest-stats.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-score.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-raw.json
/home/alex/Documents/LLM-RGB/render.ts:43
scoreData.forEach((item: any) => {
          ^
TypeError: Cannot read properties of undefined (reading 'push')
    at /home/alex/Documents/LLM-RGB/render.ts:63:33
    at Array.forEach (<anonymous>)
    at /home/alex/Documents/LLM-RGB/render.ts:62:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/alex/Documents/LLM-RGB/render.ts:43:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/home/alex/Documents/LLM-RGB/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/home/alex/Documents/LLM-RGB/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
```

12. Latest error from `step11` indicates that the path of `testcases` (It is finding `/LLM-RGB/testcases/testcases/001_requirement_check_prompt.txt` and there is an error on the path which concatenates `testcases` twice) is not correctly configured in this project, further revision is needed.


## Environment
1. Ubuntu 20.04 LTS
2. Node.js v18.14.2
3. NPM version 9.5.0

**Comment by Ezharjan** [comment]
Finally, by changing all the `testcases` in the path `file://testcases/00xxx.txt` described in each txt file, the error occurred again after running `npm start`:
```
=========================================================================================================================================================================================================
✔ Evaluation complete.

Run promptfoo view to use the local web viewer
Run promptfoo share to create a shareable URL
Run promptfoo feedback to share feedback with the developers of this tool
=========================================================================================================================================================================================================
Successes: 15
Failures: 270
Token usage: Total 0, Prompt 0, Completion 0, Cached 0
Done.

> llm-rgb@1.0.0 render
> ts-node generateEvalScore.ts && ts-node render.ts

Data loaded from JSON file: /home/alex/.promptfoo/output/latest.json
Successfully wrote testStats to /home/alex/.promptfoo/output/latest-stats.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-score.json
Successfully wrote scores to /home/alex/.promptfoo/output/latest-raw.json
/home/alex/Documents/LLM-RGB/render.ts:43
scoreData.forEach((item: any) => {
          ^
TypeError: Cannot read properties of undefined (reading 'push')
    at /home/alex/Documents/LLM-RGB/render.ts:63:33
    at Array.forEach (<anonymous>)
    at /home/alex/Documents/LLM-RGB/render.ts:62:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/alex/Documents/LLM-RGB/render.ts:43:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module.m._compile (/home/alex/Documents/LLM-RGB/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .ts] (/home/alex/Documents/LLM-RGB/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
(base) alex@fst-computer:~/Documents/LLM-RGB$ 
```

**Comment by zhlmmc** [comment]
1. make sure your promptfoo version is newer than 0.34.1: promptfoo -v
2. Your log shows no token usage: Token usage: Total 0, Prompt 0, Completion 0, Cached 0 . Which is not as expected. Please  upload "/home/alex/.promptfoo/output/latest.json" for triage.
3. Upload your promptfooconfig.yaml (delete key info)
